version: '3.9'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: spina_app_development
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    command: bash -c "bundle check || bundle install && rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  gem_cache: